### ISSUE TITLE
Double highlighted scoreboard result

### ISSUE THREAD

**Issue by edbaedba** [sytac/play#10]
When looking at the scoreboard after having taken the quiz, I only expect to see my result highlighted. However, I sometimes see two highlighted results. 

<img width="1117" alt="screen shot 2016-10-23 at 14 28 15" src="https://cloud.githubusercontent.com/assets/21814871/19626245/70526114-992d-11e6-9d3c-83ca304ed881.png">

**Comment by Industrial** [comment]
I'll let you close the tickets @edbaedba

**Comment by Industrial** [comment]
This one should be fixed

**Comment by jpa458** [comment]
I've not experienced this yet but it wasn't consistently reproducible in the first place - leaving open for now

**Comment by jpa458** [comment]
Not fixed. Manuel came across this but we cant reproduce.

**Comment by jpa458** [comment]
Reproduceable - users with the same email address are highlighted - when highlighting a result after a test we should highlight the result just taken.

**Comment by Industrial** [comment]
I think I got it now, it's comparing id's now and not email. Every entry's ID is different.

**Comment by jpa458** [comment]
Fixed
