### ISSUE TITLE
In chrome if I tab out of the browser tab to another tab the timer is paused...giving me more time to think!

### ISSUE THREAD

**Issue by jpa458** [sytac/play#19]
I expect the time to timeout even if I leave the tab/browser

**Comment by Industrial** [comment]
@pmikhailovskii: You were working on this? What is the status?

**Comment by RamonGebben** [comment]
You could also look into service workers for this. Since their lifecycle extends beyond the tab.

https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API

**Comment by Industrial** [comment]
I'll take this one

**Comment by Industrial** [comment]
I can't reproduce this bug. If I go to a different tab and back in Chrome the counter just keeps on ticking.

**Comment by pmikhailovskii** [comment]
It has been fixed by me

Kind regards,
Pavel Mikhailovskii

**Comment by jpa458** [comment]
fixed
