### ISSUE TITLE
Fix the languages/logos

### ISSUE THREAD

**Issue by jpa458** [sytac/play#25]
We have android, java, javascript, closure and scala.

Ed got SVG logos from the internet to add to the flyer - I'll ask him to upload the flyer you should be able to find the logos. Also add a mouse over on the logos.

**Comment by edbaedba** [comment]
Java, https://worldvectorlogo.com/nl/logo/java-duke
Scala, https://worldvectorlogo.com/nl/logo/scala-4
Clojure, http://seeklogo.com/vector-logo/272968/clojure
JS, https://worldvectorlogo.com/nl/logo/javascript
Android, https://worldvectorlogo.com/nl/logo/android

**Comment by RamonGebben** [comment]
By adding logo's in all different colors I have the feeling that we will break the design. 
Maybe go for a uniform set like this:

https://www.iconfinder.com/iconsets/scripting-and-programming-languages

**Comment by Industrial** [comment]
Should be fixed.

**Comment by jpa458** [comment]
Fixed
