### ISSUE TITLE
Problems with the new theme

### ISSUE THREAD

**Issue by Industrial** [sytac/play#26]
Hi. I think the new theme has some problems:
- PersonForm
  - There is no error style for form input validation.
  - The stars indicating a field is required are very unreadable.
- Quiz
  - The timer width is broken.
  - The blockquotes / indents look very out of place. I don't think we should have these at all.
- ScoreBoard
  - The highlighted table entry is no longer highlighted.

**Comment by RamonGebben** [comment]
Sure I'll take a look next week.

**Comment by jpa458** [comment]
Some additional corrections 

Persion Form : change Font to non bold

Quiz
- Adjust also the timer bar height : to match roughly the current height of block (ex double height)
- Remove the second vertical grey bar that is shown next to the question block (or remove completely if necessary)
- Answers : Change font to non bold

Scoreboard
- Add the sytac logo - like on the landing page.
- This will be displayed full screen on the TV so we need to increase the fonts to make the board more visible. Any suggestions to "jazz" it up are welcome.

**Comment by jpa458** [comment]
Ramon, Pawel is going to try and pick these up as he has more time than yourself at the moment I guess!

**Comment by jpa458** [comment]
@RamonGebben - pls see slack - just want to make sure you have time for this?
