### ISSUE TITLE
I selected Javascript as quiz type but Node appears in the scoreboard, Python also appears

### ISSUE THREAD

**Issue by jpa458** [sytac/play#28]

**Comment by jpa458** [comment]
I also see Python in the scoreboard

**Comment by jpa458** [comment]
Interests and Quiz types are 2 different concepts. Interests are purely informational.

The interests are 
.Net
Angular
Android
ios
scala
react
node
java
clojure
javascript

The quiz types are:
java
javascript
scala
clojure
android

**Comment by Industrial** [comment]
Should be fixed.

**Comment by jpa458** [comment]
Fixed
