### ISSUE TITLE
Back button bug

### ISSUE THREAD

**Issue by edbaedba** [sytac/play#3]
When pressing "back" in the browser in the leaderboard page, I go back to the question. However, I expect to to go back to the start-screen.

**Comment by Industrial** [comment]
I'm not sure this is fixable, other then using the provided back button. The last page you visited was the question, not the start-screen. I can't change the browser's back behaviour.

**Comment by Industrial** [comment]
Should be fixed.

**Comment by jpa458** [comment]
Fixed
