### ISSUE TITLE
Secure the API calls that deliver sensitive information (emails, answers)

### ISSUE THREAD

**Issue by jpa458** [sytac/play#31]

**Comment by jpa458** [comment]
If not a quick win leave this until after conference

**Comment by jpa458** [comment]
Tom We have some time now so lets pick this up - secure as much as possible so that the items discussed in slack cannot be hacked. Ramon is proposing a solution there

**Comment by Industrial** [comment]
Deployed.

**Comment by jpa458** [comment]
Looks fixed I dont see the email in the scoreboard REST results and I cannot access the questions API - closing
