### ISSUE TITLE
Change text on the Start Quiz page

### ISSUE THREAD

**Issue by jpa458** [sytac/play#34]
From:
When you press start, the game will start. Answer as many questions correctly as you can before the time runs out!

To:
Thanks for taking the Sytac Dev Quiz, we're looking forward to seeing how well you stack up!  
You will have 3 minutes to answer as many questions correctly as you can.  
Prizes will be awarded at 17h by the Sytac stand, see you then and good luck!

**Comment by pmikhailovskii** [comment]
Done

**Comment by jpa458** [comment]
Fixed
