### ISSUE TITLE
Short name bug 

### ISSUE THREAD

**Issue by edbaedba** [sytac/play#4]
When entering my short name "Ed" on the starting page, I get a "2 characters minimum error". Howevery, there are people with just 2 character names, such as "Ed" and they should not get this error.

**Comment by Industrial** [comment]
Should be fixed.

**Comment by jpa458** [comment]
main issue is fixed but the validation message still shows "...longer than 2 characters.." which is now incorrect because we accept 2 characters

**Comment by Industrial** [comment]
Whoops, right.

**Comment by Industrial** [comment]
Should be fixed now

**Comment by jpa458** [comment]
Fixed, closing
