### ISSUE TITLE
Cancelling quiz 

### ISSUE THREAD

**Issue by edbaedba** [sytac/play#6]
When I cancel the quiz half-way, I still see myself on the scoreboard (without a score). However, unfinished quizes should not be ranked on the scoreboard.

**Comment by Industrial** [comment]
This one should be fixed with https://github.com/sytac/play/commit/c1ef83939077ded311ca6b283818a2131c9b2cd3

**Comment by jpa458** [comment]
Not fixed (I "cancel" by closing the browser) - also candidate is listed on the scoreboard even before completing the quiz.

**Comment by Industrial** [comment]
Should be fixed

**Comment by jpa458** [comment]
Fixed, closing
