### ISSUE TITLE
Interest color bug 

### ISSUE THREAD

**Issue by edbaedba** [sytac/play#8]
When I select an "interest" on the homescreen the text color changes to green, when I de-select it, the text stays green. I expect that the text turns back to black.

**Comment by Industrial** [comment]
This is pretty hard to fix, as it's linked to the workings of the library.

What I could do instead is try to make it always black, since it is not a required field any way.

**Comment by Industrial** [comment]
Should be fixed

**Comment by jpa458** [comment]
Verified
