### ISSUE TITLE
Existing questions

### ISSUE THREAD

**Issue by edbaedba** [sytac/play#9]
Please add the questions that are in the Clojure quiz. You can find them [here](https://bitbucket.org/sytac-internal/conference-quiz/src/11153e6e28a7/src/cljs/clojurequiz/data/?at=master) on bitbucked. I know it will take same time to translate Clojurescript to js maar dat moet je wel lukken.

**Comment by Industrial** [comment]
Is this one done?

**Comment by jpa458** [comment]
Done for js and java, Pawel is importing the closure questions, Edgar is busy with obtaining android and Jack Tol is going to provide scala questions.

**Comment by pmikhailovskii** [comment]
I've imported existing Scala, Clojure and Android questions.
I had to throw away questions with multiple valid answers, (like "Which
statements are correct?") , so we only have a few (questions per topic.

Kind regards,
Pavel Mikhailovskii

**Comment by jpa458** [comment]
Scala and Android questions are comming. closure not so we have discussed a solution for this that pawel is working on

**Comment by jpa458** [comment]
Scala and Android questions have been delivered to Pawel

**Comment by Industrial** [comment]
@pmikhailovskii Is this one done? Then you can close it =)
